# Generated by Django 4.2.16 on 2026-08-18 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='Face embedding vector (list of floats).')),
                ('model_name', models.CharField(help_text='Backend that produced the embedding. Vectors from different models are not comparable.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'face enrollment',
                'verbose_name_plural': 'face enrollments',
            },
        ),
    ]
