# Generated by Django 4.2.16 on 2026-08-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set when the course is archived. Archiving hides it from the active lists and blocks new sessions; nothing is deleted, so past attendance stays intact and auditable.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
